### ISSUE TITLE
`have_body_text` with URL now failing after upgrading `mail` gem from 2.6.6 to 2.7.0

### ISSUE THREAD

**Issue by bobwhitelock** [email-spec/email-spec#202]
I have an app which has a test including the following:

```ruby
    user_reset_complete_path = reset_password_complete_path(
      user_id: user.id,
      token: user.confirmation_token
    )

    reset_start_email = ActionMailer::Base.deliveries.first
    expect(reset_start_email).to have_subject(/Reset your password/)
    expect(reset_start_email).to have_body_text(
      /#{Regexp.escape(user_reset_complete_path)}/
    )
```

Previously this test was passing fine, however after recently `bundle update`ing the second expectation was failing with the following error:

```
password reset process
  a user can go through the full process and receive a new password (FAILED - 1)

Failures:

  1) password reset process a user can go through the full process and receive a new password
     Failure/Error:
       expect(reset_start_email).to have_body_text(
         /#{Regexp.escape(user_reset_complete_path)}/
       )
     
       expected the body to match /\/reset\-password\/complete\?token=7f12f6b9edeaf1931b8ff1da3b0ee33fe21e4283&user_id=381/, but did not.  Actual body was: "<p>Someone, hopefully you, requested we send you a link to reset your password:</p>\n\n<p>\n  <a href=\"http://localhost:3000/reset-password/complete?token=7f12f6b9edeaf1931b8ff1da3b0ee33fe21e4283user_id=381\">Reset my password</a>\n</p>\n\n<p>If you didn't request this, ignore this email. Your password will not be reset unless this link is clicked.</p>\n"
     # ./spec/features/password_resets_spec.rb:30:in `block (2 levels) in <top (required)>'

Finished in 1.5 seconds (files took 2.21 seconds to load)
1 example, 1 failure
```

After investigating I managed to narrow the failure down to this change in my `Gemfile.lock`:

```diff
182,183c182,183
<     mail (2.7.0)
<       mini_mime (>= 0.1.1)
---
>     mail (2.6.6)
>       mime-types (>= 1.16, < 4)
184a185,187
>     mime-types (3.1)
>       mime-types-data (~> 3.2015)
>     mime-types-data (3.2016.0521)
```

The error appears to be due to the expected URL including `&` between the parameters, but the URL as seen by `email_spec` does not. However if I change the expectation to just check the email includes the URL directly, like this:

```ruby
expect(reset_start_email.to_s).to include(user_reset_complete_path)
```

then the expectation passes as expected. The URL also still looks correct if I view an email directly. This makes me suspect there's some issue with how `email_spec` is interpreting the email body after the update to `mail`.

I'm not entirely certain of the cause, or whether the problem is actually with `email_spec`, or instead with `mail` or something else interacting with these. If you think the problem might be on your end I can try and provide you with more info or reproduce this more minimally. Thanks :slightly_smiling_face:.

**Comment by emilford** [comment]
I have a similar issue using the `have_body_text` matcher.

The issue appears to be related to the [html_entities](https://github.com/threedaymonk/htmlentities) gem. It seems to no longer be able to correctly decode the `default_part.body` used in the `HaveBodyText` matcher. See [here](https://github.com/email-spec/email-spec/blob/c719a6fef8ee1ed6acb72da02d13c6626132e0ca/lib/email_spec/mail_ext.rb#L7) and [here](https://github.com/email-spec/email-spec/blob/master/lib/email_spec/matchers.rb#L289).

If I run a simple string with "&#39;", the output correctly contains an apostrophe. If I, however, run a standard email body containing "&#39;" through (as this gem does), the apostrophe is stripped out. 

So in my case, a test asserting the body text contains a string with an apostrophe (e.g., "Bob's Crab Shack") fails to match because the email body text compared against contains the matching text but with the apostrophe removed (i.e., "Bobs Crab Shack").

When I get some more time, I'll dig into it a bit more.

**Comment by jankeesvw** [comment]
I'm having this exact same issue. Is there a reason why #207 is not merged?

**Comment by irmela** [comment]
#207 just got merged 🎉
